version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nolp
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    depends_on:
      - "db"
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - "db"
      - "redis"
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "redis"
      - "server"